name: sg_cli
description: CLI tool for rapidly generating code for Flutter projects with BLoC.
version: 1.0.5
homepage: "https://github.com/solguruz/sg_cli"

environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.7.0
  package_config: ^2.2.0
  pub_semver: ^2.2.0
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0

executables:
  sg: